<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>{TargetFramework}</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="ExternalServices\" />
    <Folder Include="Messaging\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="{efVersion}" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="{efVersion}" />
	  <!--#if (databaseProvider == "MS SQL Server")-->
	  <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="{efVersion}" />
	  <!--#endif-->

	  <!--#if (databaseProvider == "PostgreSQL")-->
	  <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="{PostgreSQLVersion}" />
	  <!--#endif-->
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="{efToolVersion}">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CleanCodeScaffold.Domain\CleanCodeScaffold.Domain.csproj" />
  </ItemGroup>

</Project>
